version: "3.8"

services:
  app:
    build: .
    expose:
      - 5001
    ports:
      - "5001:5001"
    volumes:
      - db-data:/app/instance
    environment:
      - FLASK_APP=myapp
      - FLASK_ENV=development
    restart: always

volumes:
  db-data: